# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from opencv_services/box_and_target_positionRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class box_and_target_positionRequest(genpy.Message):
  _md5sum = "56bbf0a053309bcc0970665e272a9876"
  _type = "opencv_services/box_and_target_positionRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 box_id  # Request: ID of the selected box
"""
  __slots__ = ['box_id']
  _slot_types = ['int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       box_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(box_and_target_positionRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.box_id is None:
        self.box_id = 0
    else:
      self.box_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.box_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.box_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.box_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.box_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from opencv_services/box_and_target_positionResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class box_and_target_positionResponse(genpy.Message):
  _md5sum = "27c2d0218f4344d478cf0e807ec602fe"
  _type = "opencv_services/box_and_target_positionResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point box_position  # Response: 3D position of the box
geometry_msgs/Point target_position  # Response: 3D position of the target
float32 width  # Width of the bounding box
float32 height  # Height of the bounding box
float32 angle  # Angle of the bounding box



================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['box_position','target_position','width','height','angle']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       box_position,target_position,width,height,angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(box_and_target_positionResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.box_position is None:
        self.box_position = geometry_msgs.msg.Point()
      if self.target_position is None:
        self.target_position = geometry_msgs.msg.Point()
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.angle is None:
        self.angle = 0.
    else:
      self.box_position = geometry_msgs.msg.Point()
      self.target_position = geometry_msgs.msg.Point()
      self.width = 0.
      self.height = 0.
      self.angle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d3f().pack(_x.box_position.x, _x.box_position.y, _x.box_position.z, _x.target_position.x, _x.target_position.y, _x.target_position.z, _x.width, _x.height, _x.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box_position is None:
        self.box_position = geometry_msgs.msg.Point()
      if self.target_position is None:
        self.target_position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.box_position.x, _x.box_position.y, _x.box_position.z, _x.target_position.x, _x.target_position.y, _x.target_position.z, _x.width, _x.height, _x.angle,) = _get_struct_6d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d3f().pack(_x.box_position.x, _x.box_position.y, _x.box_position.z, _x.target_position.x, _x.target_position.y, _x.target_position.z, _x.width, _x.height, _x.angle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box_position is None:
        self.box_position = geometry_msgs.msg.Point()
      if self.target_position is None:
        self.target_position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.box_position.x, _x.box_position.y, _x.box_position.z, _x.target_position.x, _x.target_position.y, _x.target_position.z, _x.width, _x.height, _x.angle,) = _get_struct_6d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d3f = None
def _get_struct_6d3f():
    global _struct_6d3f
    if _struct_6d3f is None:
        _struct_6d3f = struct.Struct("<6d3f")
    return _struct_6d3f
class box_and_target_position(object):
  _type          = 'opencv_services/box_and_target_position'
  _md5sum = '24f75c68c4ed789ee1229b48052db0b6'
  _request_class  = box_and_target_positionRequest
  _response_class = box_and_target_positionResponse
