// Generated by gencpp from file opencv_services/box_positionRequest.msg
// DO NOT EDIT!


#ifndef OPENCV_SERVICES_MESSAGE_BOX_POSITIONREQUEST_H
#define OPENCV_SERVICES_MESSAGE_BOX_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opencv_services
{
template <class ContainerAllocator>
struct box_positionRequest_
{
  typedef box_positionRequest_<ContainerAllocator> Type;

  box_positionRequest_()
    : box_id(0)  {
    }
  box_positionRequest_(const ContainerAllocator& _alloc)
    : box_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _box_id_type;
  _box_id_type box_id;





  typedef boost::shared_ptr< ::opencv_services::box_positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencv_services::box_positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct box_positionRequest_

typedef ::opencv_services::box_positionRequest_<std::allocator<void> > box_positionRequest;

typedef boost::shared_ptr< ::opencv_services::box_positionRequest > box_positionRequestPtr;
typedef boost::shared_ptr< ::opencv_services::box_positionRequest const> box_positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencv_services::box_positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencv_services::box_positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opencv_services::box_positionRequest_<ContainerAllocator1> & lhs, const ::opencv_services::box_positionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.box_id == rhs.box_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opencv_services::box_positionRequest_<ContainerAllocator1> & lhs, const ::opencv_services::box_positionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opencv_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::opencv_services::box_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_services::box_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_services::box_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_services::box_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_services::box_positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_services::box_positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencv_services::box_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56bbf0a053309bcc0970665e272a9876";
  }

  static const char* value(const ::opencv_services::box_positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56bbf0a053309bccULL;
  static const uint64_t static_value2 = 0x0970665e272a9876ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencv_services::box_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencv_services/box_positionRequest";
  }

  static const char* value(const ::opencv_services::box_positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencv_services::box_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 box_id  # Request: ID of the selected box\n"
;
  }

  static const char* value(const ::opencv_services::box_positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencv_services::box_positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.box_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct box_positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencv_services::box_positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencv_services::box_positionRequest_<ContainerAllocator>& v)
  {
    s << indent << "box_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.box_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCV_SERVICES_MESSAGE_BOX_POSITIONREQUEST_H
